services:
  _defaults:
    public: true
    
  prestashop.module.dottgnotices.service.authorization_bank:
    class: 'PrestaShop\Module\Dottgnotices\Service\AuthorizationBank'
    arguments: ['@prestashop.adapter.legacy.configuration'] 


  
   