services:
  _defaults:
    public: true   

  # Demo configuration text form
  prestashop.module.dottgnotices.form.type.configuration_text:
    class: 'PrestaShop\Module\Dottgnotices\Form\ConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.dottgnotices.form.configuration_text_data_configuration:
    class: PrestaShop\Module\Dottgnotices\Form\ConfigurationTextDataConfiguration
    arguments: ['@prestashop.adapter.legacy.configuration']

  prestashop.module.dottgnotices.form.configuration_text_form_data_provider:
    class: 'PrestaShop\Module\Dottgnotices\Form\ConfigurationTextFormDataProvider'
    arguments:
      - '@prestashop.module.dottgnotices.form.configuration_text_data_configuration'

  prestashop.module.dottgnotices.form.configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dottgnotices.form.configuration_text_form_data_provider'
      - 'PrestaShop\Module\Dottgnotices\Form\ConfigurationFormType'
      - 'Configuration'
  
   